nodeLinker: node-modules

npmRegistryServer: "https://registry.yarnpkg.com"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-postinstall.cjs
    spec: "https://raw.githubusercontent.com/gravitywelluk/yarn-plugin-postinstall/master/bundles/%40yarnpkg/plugin-postinstall.js"

postinstall: rm -rf ./node_modules/@chiubaka/nx-plugin

unsafeHttpWhitelist: "[]"

yarnPath: .yarn/releases/yarn-3.2.2.cjs
