services:
  registry:
    container_name: genesis_registry
    image: verdaccio/verdaccio
    ports:
      - 4873:4873
    volumes:
      - "./verdaccio/config:/verdaccio/conf"
      - "./verdaccio/storage:/verdaccio/storage"
      - "./verdaccio/plugins:/verdaccio/plugins"
