import {
  formatFiles,
  getPackageManagerCommand,
  getWorkspaceLayout,
  names,
  readWorkspaceConfiguration,
  Tree,
  updateWorkspaceConfiguration,
} from "@nrwl/devkit";
import { PackageJson as PackageJsonType } from "nx/src/utils/package-json";

import PackageJson from "../../../package.json";
import { exec } from "../../utils";
import { gitGenerator } from "../git";
import { lintingGenerator } from "../linting";
import { noOpTask } from "../tasks";
import { PresetGeneratorSchema } from "./presetGenerator.schema";

interface NormalizedSchema extends PresetGeneratorSchema {
  projectName: string;
  projectRoot: string;
  projectDirectory: string;
  parsedTags: string[];
}

export async function presetGenerator(
  tree: Tree,
  options: PresetGeneratorSchema,
) {
  options = normalizeOptions(tree, options);

  modifyWorkspaceLayout(tree);

  const installTask = options.skipInstall
    ? noOpTask
    : reinstallPackagesWithYarn(tree);
  const lintingTask = lintingGenerator(tree);
  const gitTask = setUpGit(tree);

  await formatFiles(tree);

  return async () => {
    await installTask();
    await lintingTask();
    await gitTask();
  };
}

function normalizeOptions(
  tree: Tree,
  options: PresetGeneratorSchema,
): NormalizedSchema {
  const name = names(options.name).fileName;
  const projectDirectory = options.directory
    ? `${names(options.directory).fileName}/${name}`
    : name;
  const projectName = projectDirectory.replace(new RegExp("/", "g"), "-");
  const projectRoot = `${getWorkspaceLayout(tree).libsDir}/${projectDirectory}`;
  const parsedTags = options.tags
    ? options.tags.split(",").map((s) => s.trim())
    : [];

  return {
    ...options,
    projectName,
    projectRoot,
    projectDirectory,
    parsedTags,
  };
}

function modifyWorkspaceLayout(tree: Tree) {
  const workspaceConfig = readWorkspaceConfiguration(tree);
  updateWorkspaceConfiguration(tree, {
    ...workspaceConfig,
    workspaceLayout: {
      appsDir: "e2e",
      libsDir: "packages",
    },
    cli: {
      packageManager: "yarn",
    },
  });

  tree.delete("apps");
  tree.delete("libs");

  tree.write("e2e/.gitkeep", "");
  tree.write("packages/.gitkeep", "");
}

function reinstallPackagesWithYarn(tree: Tree) {
  tree.delete("package-lock.json");

  const pmc = getPackageManagerCommand("yarn");

  return async () => {
    await exec(pmc.install, {
      cwd: tree.root,
    });
  };
}

function setUpGit(tree: Tree) {
  const { name: packageName, version: packageVersion } =
    PackageJson as PackageJsonType;
  const packageInfo = `${packageName}@${packageVersion}`;
  return gitGenerator(tree, {
    commitMessage: `Initial commit with files generated by ${packageInfo} preset.`,
    prePushCommand: "nx affected --target=test",
  });
}
