import {
  formatFiles,
  generateFiles,
  getPackageManagerCommand,
  readWorkspaceConfiguration,
  Tree,
  updateJson,
  updateWorkspaceConfiguration,
} from "@nrwl/devkit";
import { rmSync } from "fs-extra";
import path from "node:path";
import { PackageJson as PackageJsonType } from "nx/src/utils/package-json";

import PackageJson from "../../../../package.json";
import { generatorLogger as logger } from "../../../logger";
import { exec } from "../../../utils";
import { ciGenerator } from "../ci";
import { gitGenerator } from "../git";
import { lintingGenerator } from "../linting";
import { readmeGenerator } from "../readme";
import { noOpTask } from "../tasks";
import { testingGenerator } from "../testing";
import { tsconfigGenerator } from "../tsconfig";
import { PresetGeneratorSchema } from "./presetGenerator.schema";

export async function presetGenerator(
  tree: Tree,
  options: PresetGeneratorSchema,
) {
  logger.info(
    `Generating @chiubaka/nx-plugin workspace preset with options:\n${JSON.stringify(
      options,
      undefined,
      2,
    )}`,
  );
  modifyWorkspaceLayout(tree);

  const installTask = reinstallPackagesWithYarn(tree, options);
  const tsconfigTask = await tsconfigGenerator(tree);
  const lintingTask = await lintingGenerator(tree, { packageManager: "yarn" });
  const testingTask = await testingGenerator(tree);
  ciGenerator(tree);
  readmeGenerator(tree, options);
  const gitTask = await setUpGit(tree, options);

  await formatFiles(tree);

  return async () => {
    logger.info("Running post-processing tasks for preset generator");

    await installTask();
    await tsconfigTask();
    await lintingTask();
    await testingTask();
    await gitTask();
  };
}

function modifyWorkspaceLayout(tree: Tree) {
  logger.info("Modifying workspace layout to conform to e2e/ and packages/");

  const workspaceConfig = readWorkspaceConfiguration(tree);
  updateWorkspaceConfiguration(tree, {
    ...workspaceConfig,
    workspaceLayout: {
      appsDir: "e2e",
      libsDir: "packages",
    },
    cli: {
      packageManager: "yarn",
    },
  });

  updateJson(tree, "package.json", (packageJson: PackageJsonType) => {
    packageJson.workspaces = {
      packages: ["packages/*"],
    };

    return packageJson;
  });

  tree.delete("apps");
  tree.delete("libs");

  tree.write("e2e/.gitkeep", "");
  tree.write("packages/.gitkeep", "");
}

function reinstallPackagesWithYarn(tree: Tree, options: PresetGeneratorSchema) {
  const { skipInstall, registry } = options;

  if (skipInstall) {
    return noOpTask;
  }

  tree.delete("package-lock.json");
  generateFiles(tree, path.join(__dirname, "./files"), ".", {});

  const pmc = getPackageManagerCommand("yarn");

  return async () => {
    logger.info("Reinstalling packages with yarn");

    rmSync(path.join(tree.root, "node_modules"), {
      force: true,
      recursive: true,
    });

    await exec(`yarn set version berry`, {
      cwd: tree.root,
    });

    if (registry) {
      logger.info(`Using registry ${registry}`);

      await exec(`yarn config set npmRegistryServer ${registry}`, {
        cwd: tree.root,
      });

      const registryUrl = new URL(registry);

      if (registryUrl.protocol === "http:") {
        await exec(
          `yarn config set unsafeHttpWhitelist ${registryUrl.hostname}`,
          {
            cwd: tree.root,
          },
        );
      }
    }

    await exec(`${pmc.install} --no-immutable`, {
      cwd: tree.root,
    });
  };
}

function setUpGit(tree: Tree, options: PresetGeneratorSchema) {
  const generatorPackageInfo = getGeneratorPackageInfo();

  return gitGenerator(tree, {
    commitMessage: `Initial commit with files generated by ${generatorPackageInfo} preset.`,
    preCommitCommand: "yarn lint:staged",
    prePushCommand: "nx affected --target=test",

    organization: options.workspaceScope,
    repositoryName: options.workspaceName,
    repositoryDescription: options.description,
    privateRepository: true,
    enableCircleCiStatusChecks: true,
    enableCodecovStatusChecks: true,

    skipGitHub: options.skipGitHub,
  });
}

function getGeneratorPackageInfo() {
  const { name: packageName, version: packageVersion } =
    PackageJson as PackageJsonType;
  return `${packageName}@${packageVersion}`;
}
