%YAML 1.1
---
version: 2.1

constants:
  # Semantic versioning RegEx from https://semver.org/#is-there-a-suggested-regular-expression-regex-to-check-a-semver-string
  semver-regex: &semver-regex /^v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$/

orbs:
  chiubaka: chiubaka/circleci-orb@0.6.1

filters:
  semver-tags: &semver-tags
    tags:
      only: *semver-regex
  ignore-branches: &ignore-branches
    branches:
      ignore: /.*/

workflows:
  lint-build-test-publish:
    jobs:
      - chiubaka/lint:
          name: lint
          filters:
            <<: *semver-tags
      - chiubaka/build:
          name: build
          filters:
            <<: *semver-tags
      - chiubaka/test:
          name: test
          configure-git-user: true
          filters:
            <<: *semver-tags
      - chiubaka/publish:
          context:
            - npm-publishing
          requires:
            - lint
            - build
            - test
          filters:
            <<: *ignore-branches
            <<: *semver-tags
