%YAML 1.1
---
version: 2.1

constants:
  # Semantic versioning RegEx modified from https://semver.org/#is-there-a-suggested-regular-expression-regex-to-check-a-semver-string
  semver-regex: &semver-regex /^(\w+-)+v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$/

orbs:
  chiubaka: chiubaka/circleci-orb@dev:031d2b06235f149531a155b10400aeccd17bc913

filters:
  semver-tags: &semver-tags
    tags:
      only: *semver-regex
  ignore-branches: &ignore-branches
    branches:
      ignore: /.*/

workflows:
  lint-build-test-deploy:
    jobs:
      # - chiubaka/lint:
      #     name: lint
      #     yarn-berry: true
      #     filters:
      #       <<: *semver-tags
      - chiubaka/build:
          name: build
          yarn-berry: true
          cleanup-steps:
            - persist_to_workspace:
                root: .
                paths:
                  # Save the NX cache so subsequent jobs can read from cache
                  - node_modules.cache/nx
                  # Save built packages so they can be used by downstream jobs
                  - dist
          filters:
            <<: *semver-tags
      - chiubaka/test:
          name: test
          configure-git-user: true
          yarn-berry: true
          setup-steps:
            - attach_workspace:
                at: .
            # This is needed because, otherwise, attempts to globally install
            # npm modules will fail due to permission denied.
            - run:
                name: Set NPM Prefix
                command: echo "export NPM_CONFIG_PREFIX=$HOME/.local" >> $BASH_ENV
            - run:
                name: Start Verdaccio
                command: yarn verdaccio --config ./verdaccio/config/config.local.yaml
                background: true
          cleanup-steps:
            - persist_to_workspace:
                root: .
                paths:
                  # Save the NX cache so subsequent jobs can read from cache
                  - node_modules/.cache/nx
                  # Save generated Genesis E2E workspace template to speed up downstream tests
                  - tmp/nx-e2e/genesis-e2e
          requires:
            - build
          filters:
            <<: *semver-tags
      - ios-e2e:
          requires:
            - test
        # requires:
        # - lint
        # - build
        # - test
      - chiubaka/deploy:
          name: deploy
          task-name: Publish to NPM
          yarn-berry: true
          context:
            - npm-publishing
          requires:
            - ios-e2e
          filters:
            <<: *ignore-branches
            <<: *semver-tags

jobs:
  ios-e2e:
    executor: chiubaka/macos
    steps:
      - checkout
      - chiubaka/setup-macos:
          yarn-berry: true
      - attach_workspace:
          at: .
      - run:
          name: Start Verdaccio
          command: yarn verdaccio --config ./verdaccio/config/config.local.yaml
          background: true
      - run:
          name: Run iOS E2E tests
          command: yarn run e2e:ios:affected
