%YAML 1.1
---
version: 2.1

constants:
  # Semantic versioning RegEx modified from https://semver.org/#is-there-a-suggested-regular-expression-regex-to-check-a-semver-string
  semver-regex: &semver-regex /^(\w+-)+v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$/

orbs:
  chiubaka: chiubaka/circleci-orb@0.11.4
  react-native: react-native-community/react-native@7.1.1
  node: circleci/node@5.1.0

filters:
  semver-tags: &semver-tags
    tags:
      only: *semver-regex
  ignore-branches: &ignore-branches
    branches:
      ignore: /.*/

workflows:
  lint-build-test-deploy:
    jobs:
      # - chiubaka/lint:
      #     name: lint
      #     yarn-berry: true
      #     filters:
      #       <<: *semver-tags
      # - chiubaka/build:
      #     name: build
      #     yarn-berry: true
      #     filters:
      #       <<: *semver-tags
      # - chiubaka/test:
      #     executor: chiubaka/machine
      #     name: test
      #     configure-git-user: true
      #     docker-compose: true
      #     wait-for-docker-services:
      #       - chiubaka/wait-for-docker-service:
      #           container-name: genesis_registry
      #           url: http://localhost:4873/healthcheck
      #     yarn-berry: true
      #     filters:
      #       <<: *semver-tags
      - ios-e2e
        # requires:
        # - lint
        # - build
        # - test
      - chiubaka/deploy:
          name: deploy
          task-name: Publish to NPM
          yarn-berry: true
          context:
            - npm-publishing
          requires:
            - ios-e2e
          filters:
            <<: *ignore-branches
            <<: *semver-tags

jobs:
  ios-e2e:
    executor:
      name: react-native/macos
      resource_class: macos.m1.medium.gen1
      xcode_version: 14.3.1
    steps:
      - checkout
      - react-native/setup_macos_executor:
          node_version: "16"
      - node/install-packages:
          pkg-manager: yarn-berry
      - run:
          name: Start Verdaccio
          command: yarn verdaccio --config ./verdaccio/config/config.local.yaml
          background: true
      - run:
          name: Install Xcodes
          command: brew install xcodesorg/made/xcodes
      - run:
          name: Run iOS E2E tests
          command: yarn run e2e:ios:affected
