%YAML 1.1
---
version: 2.1

constants:
  # Semantic versioning RegEx modified from https://semver.org/#is-there-a-suggested-regular-expression-regex-to-check-a-semver-string
  semver-regex: &semver-regex /^(\w+-)+v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$/

orbs:
  chiubaka: chiubaka/circleci-orb@0.9.1

filters:
  semver-tags: &semver-tags
    tags:
      only: *semver-regex
  ignore-branches: &ignore-branches
    branches:
      ignore: /.*/

workflows:
  lint-build-test-deploy:
    jobs:
      - chiubaka/lint:
          name: lint
          yarn-berry: true
          filters:
            <<: *semver-tags
      - chiubaka/build:
          name: build
          yarn-berry: true
          filters:
            <<: *semver-tags
      - chiubaka/test:
          name: test
          configure-git-user: true
          docker-compose: true
          wait-for-docker-services:
            - chiubaka/wait-for-docker-service:
                container-name: genesis_registry_1
                url: http://localhost:4873
          yarn-berry: true
          filters:
            <<: *semver-tags
      - chiubaka/deploy:
          name: deploy
          task-name: Publish to NPM
          yarn-berry: true
          context:
            - npm-publishing
          requires:
            - lint
            - build
            - test
          filters:
            <<: *ignore-branches
            <<: *semver-tags
