import { Tree } from "@nrwl/devkit";
import { createTreeWithEmptyWorkspace } from "@nrwl/devkit/testing";

import { gitHubGenerator } from "../../../src/generators";

describe("githubGenerator", () => {
  let tree: Tree;

  beforeAll(async () => {
    tree = createTreeWithEmptyWorkspace();
    const githubTask = gitHubGenerator(tree, {
      organization: "chiubaka",
      repositoryName: "test-genesis",
      repositoryDescription: "Test repository generated by genesis",
      privateRepository: true,
    });

    await githubTask();
  });
});
