%YAML 1.1
---
version: 2.1

setup: true

orbs:
  chiubaka: chiubaka/circleci-orb@dev:alpha

constants:
  # Semantic versioning RegEx modified from https://semver.org/#is-there-a-suggested-regular-expression-regex-to-check-a-semver-string
  semver-regex: &semver-regex /^(\w+-)+v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$/

filters:
  semver-tags: &semver-tags
    tags:
      only: *semver-regex

workflows:
  dynamic-setup:
    jobs:
      - chiubaka/dynamic-setup:
          filters:
            <<: *semver-tags
